apiVersion : apps/v1
kind : Deployment
metadata :
  name : client-deployment
spec :
  replicas : 3
  selector :
    matchLabels :
      component : web
  template :
    metadata :
      labels :  # selector and the labels in template helps the deployment know it's pods to manage
        component : web
    spec :
      containers :
        - name : client
          image : stephengrider/multi-client
          ports :
            - containerPort : 3000
